name: Build and Push Docker Image for BETA branch

on:
  push:
    branches-ignore:
      - master
      - development
      - prepare-release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        id: vars
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SANITIZED_BRANCH_NAME=$(echo "${BRANCH_NAME}" | sed 's/[\/]/-/g')
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "DOCKER_TAG=${SANITIZED_BRANCH_NAME}-${TIMESTAMP}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/utopia-client:beta-${{ env.DOCKER_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/utopia-client:beta-latest
          platforms: linux/amd64,linux/arm64

      - name: Complete
        run: |
          echo "Docker image published with tags: beta-latest and beta-${{ env.DOCKER_TAG }}"
